name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/image1.png
  - assets/brain.png
  - assets/que.gif
  - assets/logo.png
  - assets/plain_bulb.png
  - assets/light_bulb.png
  - assets/trophy.gif
  - assets/congratulations.png
  - assets/fail.png
  
  
